/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-15 09:44:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import models.ProductModel;

public final class ProductPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.ProductModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Product Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("    h1 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .alert {\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        border: 1px solid transparent;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    .alert-success {\r\n");
      out.write("        color: #3c763d;\r\n");
      out.write("        background-color: #dff0d8;\r\n");
      out.write("        border-color: #d6e9c6;\r\n");
      out.write("    }\r\n");
      out.write("    .alert-danger {\r\n");
      out.write("        color: #a94442;\r\n");
      out.write("        background-color: #f2dede;\r\n");
      out.write("        border-color: #ebccd1;\r\n");
      out.write("    }\r\n");
      out.write("    .card {\r\n");
      out.write("        width: calc(20% - 20px); /* Adjust based on the number of cards per row */\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .card img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-top-left-radius: 5px;\r\n");
      out.write("        border-top-right-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .card-body {\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .card-title {\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    .card-text {\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    .btn {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding: 2px 4px;\r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("        font-size: 10px;\r\n");
      out.write("        font-weight: 400;\r\n");
      out.write("        line-height: 1.42857143;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        -ms-touch-action: manipulation;\r\n");
      out.write("        touch-action: manipulation;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("        background-image: none;\r\n");
      out.write("        border: 1px solid transparent;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-primary {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("        border-color: #007bff;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-success {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        background-color: #28a745;\r\n");
      out.write("        border-color: #28a745;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Products</h1>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");
 
    // Check if a success or error message exists in the request scope
    String successMessage = (String) request.getAttribute("successMessage");
    String errorMessage = (String) request.getAttribute("errorMessage");
    
    if (successMessage != null) {
    
      out.write("\r\n");
      out.write("        <div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("            ");
      out.print( successMessage );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 
    }
    
    if (errorMessage != null) {
    
      out.write("\r\n");
      out.write("        <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("            ");
      out.print( errorMessage );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 
    }
     
    List<ProductModel> products = (List<ProductModel>) request.getAttribute("products");
    if (products != null) {
        for (ProductModel product : products) { 
    
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Uploads/ProductPictures/");
      out.print( product.getProduct_image());
      out.write("\" class=\"card-img-top\" alt=\"");
      out.print( product.getProduct_name() );
      out.write("\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">");
      out.print( product.getProduct_name() );
      out.write("</h5>\r\n");
      out.write("            \r\n");
      out.write("            <p class=\"card-text\">Price: $");
      out.print( product.getPrice() );
      out.write("</p>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddToCartServlet\" method=\"post\">\r\n");
      out.write("            	<input type=\"hidden\" value=\"");
      out.print( product.getProduct_id());
      out.write("\"name=\"product_id\">\r\n");
      out.write("            	<input type=\"hidden\" value = 1 name=\"quantity\">\r\n");
      out.write("            	<input type=\"hidden\" value=\"");
      out.print( session.getAttribute("user_id") );
      out.write("\" name=\"user_id\">\r\n");
      out.write("            	<button type=\"submit\" class=\"btn btn-primary\">Add to cart</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <br>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/PurchaseServlet\" method=\"post\">\r\n");
      out.write("            	<input type=\"hidden\" value=\"");
      out.print( product.getProduct_id());
      out.write("\" name=\"product_id\">\r\n");
      out.write("            	<input type=\"hidden\" value = 1 name=\"quantity\">\r\n");
      out.write("            	<input type=\"hidden\" value =");
      out.print( product.getPrice() );
      out.write(" name=\"price\">\r\n");
      out.write("            	<input type=\"hidden\" value=\"");
      out.print( session.getAttribute("userId") );
      out.write("\" name=\"user_id\">\r\n");
      out.write("            	<button type=\"submit\" class=\"btn btn-success\">Buy Now</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 
        }
    } else {
    	
      out.write("\r\n");
      out.write("        <h1>No products have been added. Please add them.</h1>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
