/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-07 06:01:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/footer.jsp", Long.valueOf(1714713166078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/product.css\">\r\n");
      out.write("    <title>Products</title>\r\n");
      out.write("    <!-- Your CSS styles -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">TimZy</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Products</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">About Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">User</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- Search form -->\r\n");
      out.write("            <form class=\"d-flex\">\r\n");
      out.write("                <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("                <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- End Navbar -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card mb-4\">\r\n");
      out.write("                <a href=\"#\" class=\"card-link\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"category-image\">\r\n");
      out.write("                            <img src=\"images/product_image.jpg\" alt=\"Product image\" class=\"img-fluid rounded\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"card-title\"><a>Product Name</a></h4>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                        	<span class=\"description float-start\">Price:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Product Description</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Connectivity:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Brand Name:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Operating System</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">ScreenSize:</span>\r\n");
      out.write("                            <span class=\"description float-start\">Watch Color:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Features:</span>\r\n");
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        \r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                            <button class=\"btn btn-primary\">Add to Cart</button>\r\n");
      out.write("                            <button class=\"btn btn-success\">Buy Now</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card mb-4\">\r\n");
      out.write("                <a href=\"#\" class=\"card-link\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"category-image\">\r\n");
      out.write("                            <img src=\"images/product_image.jpg\" alt=\"Product image\" class=\"img-fluid rounded\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"card-title\"><a>Product Name</a></h4>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                        	<span class=\"description float-start\">Price:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Product Description</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Connectivity:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Brand Name:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Operating System</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">ScreenSize:</span>\r\n");
      out.write("                            <span class=\"description float-start\">Watch Color:</span><br>\r\n");
      out.write("                            <span class=\"description float-start\">Features:</span>\r\n");
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        \r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                            <button class=\"btn btn-primary\">Add to Cart</button>\r\n");
      out.write("                            <button class=\"btn btn-success\">Buy Now</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <style>\r\n");
      out.write("    /* Footer Styles */\r\n");
      out.write(".footer {\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("    padding: 50px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-container {\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-description, .contact-info {\r\n");
      out.write("    width: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-description h2, .contact-info h2 {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-description p {\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info ul li {\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom p {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <div class=\"company-description\">\r\n");
      out.write("            <h2>About TimZy</h2>\r\n");
      out.write("            <p>TimZy is a leading brand in smartwatch technology, dedicated to providing innovative and stylish wearable devices that enhance everyday life. Our commitment to quality and customer satisfaction drives us to continually push the boundaries of what's possible in wearable technology.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact-info\">\r\n");
      out.write("            <h2>Contact Us</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>Email: info@timzy.com</li>\r\n");
      out.write("                <li>Phone: +977 987726351</li>\r\n");
      out.write("                <li>Address: 123 Smartwatch Street, City, Country</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("        <p>&copy; 2024 TimZy. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write(" <!-- Assuming you have a footer.jsp file for the footer -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
